# Local Host Defender — subprocess command executor for the Citadel host machine.
#
# Provides the same execution interface as SSHConnectionManager but runs
# commands locally via PowerShell (Windows) or bash (Linux/macOS).
# No SSH, no credentials needed — the process already has OS-level access.
#
# Security model:
#   - Read-only commands: auto-execute (same whitelist as SSH)
#   - Write commands at Guardian/Observer: require user approval
#   - Write commands at Sentinel: auto-execute (logged to audit trail)
#
# Windows encoding note: NEVER use emoji in print()/logging — cp1252 crashes.

import asyncio
import logging
import os
import platform
import re
import shutil
import subprocess
import time
from dataclasses import dataclass
from typing import List, Optional

# Windows subprocess isolation flags.
# CREATE_NEW_PROCESS_GROUP: puts the child in its own process group so that
#   CTRL_C_EVENT generated by console apps (e.g. ssh-keygen prompting for a
#   passphrase) is NOT propagated to the uvicorn parent process group.
# CREATE_NO_WINDOW: suppresses any console window pop-up for GUI sessions.
#
# NOTE: We intentionally do NOT use DETACHED_PROCESS here. That flag cuts
# the child off from the parent's console entirely, which silences PowerShell's
# output pipeline ([Console]::Out becomes a null writer) even though the stdout
# PIPE is still open — all command output is lost. CREATE_NEW_PROCESS_GROUP is
# sufficient for signal isolation; the event-loop-blocking problem is solved by
# execute_command_async() (run_in_executor), so a hanging ssh-keygen just times
# out in its thread after 30 s without ever blocking asyncio heartbeats.
_WIN_CREATION_FLAGS = (
    subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.CREATE_NO_WINDOW
    if platform.system() == "Windows"
    else 0
)

logger = logging.getLogger(__name__)

_OS = platform.system()  # "Windows", "Linux", "Darwin"


@dataclass
class LocalCommandResult:
    """Result of a locally-executed command. Mirrors SSHCommandResult shape."""
    stdout: str
    stderr: str
    exit_code: int
    duration_ms: int

    @property
    def success(self) -> bool:
        return self.exit_code == 0


# ── Command execution ─────────────────────────────────────────────────

def _split_shell_tokens(command: str) -> List[str]:
    """Tokenize a shell command, stripping surrounding quotes from each token.

    Handles double-quoted strings (preserving internal spaces), single-quoted
    strings, and bare unquoted tokens.  Does NOT attempt full POSIX parsing —
    just enough to correctly split AI-generated ssh-keygen invocations.
    """
    tokens: List[str] = []
    for m in re.finditer(r'"([^"]*)"' + r"|'([^']*)'" + r"|(\S+)", command):
        tokens.append(m.group(1) if m.group(1) is not None
                      else m.group(2) if m.group(2) is not None
                      else m.group(3))
    return tokens


def _expand_env(token: str) -> str:
    """Expand shell env-var references in a single argv token.

    Windows:  $env:VARNAME  (PowerShell style, case-insensitive)
    Others:   $VARNAME / ${VARNAME}  (POSIX style via os.path.expandvars)
    """
    if _OS == "Windows":
        return re.sub(
            r"\$env:(\w+)",
            lambda m: os.environ.get(m.group(1), f"$env:{m.group(1)}"),
            token,
            flags=re.IGNORECASE,
        )
    return os.path.expandvars(token)


def _build_argv(command: str) -> List[str]:
    """Build subprocess argument list for the local OS."""
    if _OS == "Windows":
        return [
            "powershell",
            "-NonInteractive",
            "-NoProfile",
            "-Command",
            command,
        ]
    else:
        return ["bash", "-c", command]


class LocalHostDefender:
    """Execute shell commands on the local machine without SSH.

    Used when Guardian AI needs to investigate or respond to threats on the
    machine running Citadel Guardian itself (asset_id="localhost").

    All output is capped at 8 KB to prevent memory issues with verbose commands.
    """

    MAX_OUTPUT = 8_192  # bytes per stream

    def execute_command(
        self,
        command: str,
        timeout: int = 30,
    ) -> LocalCommandResult:
        """Run a command locally and return the result.

        Args:
            command:  Shell command string (PowerShell on Windows, bash elsewhere).
            timeout:  Max seconds to wait (default 30, capped at 120).

        Returns:
            LocalCommandResult with stdout, stderr, exit_code, duration_ms.

        Raises:
            TimeoutError: if the command exceeds the timeout.
            RuntimeError: if the subprocess cannot be launched.
        """
        timeout = max(5, min(int(timeout), 120))

        # ssh-keygen reads passphrase via the Windows console API (ReadConsoleW),
        # not stdin, so stdin=DEVNULL alone doesn't prevent the hang.  And
        # PowerShell 5.x silently drops empty-string args to native executables,
        # so appending `-N ""` inside a -Command string never reaches the binary.
        # Solution: bypass the shell entirely and exec ssh-keygen directly.
        if "ssh-keygen" in command.lower():
            return self._execute_ssh_keygen(command, timeout)

        argv = _build_argv(command)

        t0 = time.monotonic()
        try:
            proc = subprocess.run(
                argv,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",          # don't crash on non-UTF-8 PowerShell output
                timeout=timeout,
                stdin=subprocess.DEVNULL,  # prevent ssh-keygen passphrase hang + console signal propagation
                creationflags=_WIN_CREATION_FLAGS,  # isolate child process group on Windows
            )
            duration_ms = int((time.monotonic() - t0) * 1000)
            stdout = (proc.stdout or "")[: self.MAX_OUTPUT]
            stderr = (proc.stderr or "")[: self.MAX_OUTPUT]

            logger.debug(
                "LocalDefender executed (exit=%d, %dms): %s",
                proc.returncode, duration_ms, command[:80],
            )
            return LocalCommandResult(
                stdout=stdout,
                stderr=stderr,
                exit_code=proc.returncode,
                duration_ms=duration_ms,
            )

        except subprocess.TimeoutExpired:
            duration_ms = int((time.monotonic() - t0) * 1000)
            raise TimeoutError(
                f"Local command timed out after {timeout}s: {command[:80]!r}"
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                f"Cannot launch {'powershell' if _OS == 'Windows' else 'bash'}: {exc}"
            ) from exc
        except Exception as exc:
            raise RuntimeError(f"Local command failed: {exc}") from exc

    def _execute_ssh_keygen(self, command: str, timeout: int) -> LocalCommandResult:
        """Run ssh-keygen directly, bypassing the shell.

        PowerShell 5.x (Windows PowerShell) silently drops empty-string
        arguments when calling native executables — so `-N ""` appended inside
        a -Command string never reaches ssh-keygen.  Running the binary
        directly via a Python list avoids all shell quoting layers and
        guarantees ["-N", ""] arrives as two distinct argv slots.

        Steps:
          1. Locate the ssh-keygen binary (PATH > System32 > Git).
          2. Tokenize the command string, stripping quotes.
          3. Drop the leading "ssh-keygen" token.
          4. Expand $env:VAR (Windows) / $VAR (POSIX) per-token.
          5. Inject ["-N", ""] if -N is absent (non-interactive, no passphrase).
          6. subprocess.run([ssh_keygen_path] + args) directly.
        """
        # 1. Locate ssh-keygen binary
        ssh_keygen = shutil.which("ssh-keygen")
        if ssh_keygen is None:
            for candidate in [
                r"C:\Windows\System32\OpenSSH\ssh-keygen.exe",
                r"C:\Program Files\Git\usr\bin\ssh-keygen.exe",
                r"C:\Program Files (x86)\Git\usr\bin\ssh-keygen.exe",
            ]:
                if os.path.isfile(candidate):
                    ssh_keygen = candidate
                    break
        if ssh_keygen is None:
            raise RuntimeError(
                "ssh-keygen not found — install OpenSSH (Windows optional feature) or Git for Windows"
            )

        # 2+3. Tokenize and drop the leading "ssh-keygen[.exe]" token
        tokens = _split_shell_tokens(command)
        args = [_expand_env(tok) for tok in tokens[1:]]  # tokens[0] is the command name

        # 4. Inject -N "" if absent (guarantees non-interactive execution)
        if "-N" not in args:
            args.extend(["-N", ""])

        argv = [ssh_keygen] + args
        logger.debug("LocalDefender ssh-keygen direct: %s", argv)

        t0 = time.monotonic()
        try:
            proc = subprocess.run(
                argv,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
                stdin=subprocess.DEVNULL,
                creationflags=_WIN_CREATION_FLAGS,
            )
            duration_ms = int((time.monotonic() - t0) * 1000)
            logger.debug(
                "LocalDefender ssh-keygen (exit=%d, %dms)",
                proc.returncode, duration_ms,
            )
            return LocalCommandResult(
                stdout=(proc.stdout or "")[: self.MAX_OUTPUT],
                stderr=(proc.stderr or "")[: self.MAX_OUTPUT],
                exit_code=proc.returncode,
                duration_ms=duration_ms,
            )
        except subprocess.TimeoutExpired:
            raise TimeoutError(
                f"ssh-keygen timed out after {timeout}s: {command[:80]!r}"
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                f"Cannot launch ssh-keygen at {ssh_keygen!r}: {exc}"
            ) from exc
        except Exception as exc:
            raise RuntimeError(f"ssh-keygen failed: {exc}") from exc

    async def execute_command_async(
        self,
        command: str,
        timeout: int = 30,
    ) -> LocalCommandResult:
        """Async wrapper: runs execute_command in a thread pool executor.

        Always use this from async contexts (FastAPI handlers, ai_bridge tool
        loop) so subprocess.run() does not block the asyncio event loop.
        A blocked event loop starves WebSocket heartbeats, which triggers the
        heartbeat watchdog and causes a clean-shutdown crash after ~120s.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, self.execute_command, command, timeout)


# ── Localhost asset bootstrap helper ─────────────────────────────────

def ensure_localhost_asset(inventory) -> bool:
    """Register the local machine as asset_id='localhost' if not already present.

    Called once on startup. Idempotent — skips quietly if localhost already exists.

    Returns True if a new asset was created, False if it already existed.
    """
    if inventory.get("localhost") is not None:
        return False

    from ..intel.assets import Asset, AssetPlatform, AssetType, AssetStatus

    hostname = platform.node() or "localhost"
    os_name = _OS

    # Best-effort local IP (loopback as fallback)
    ip_address = _get_local_ip()

    asset = Asset(
        asset_id="localhost",
        name=hostname,
        platform=AssetPlatform.LOCAL,
        asset_type=AssetType.WORKSTATION,
        status=AssetStatus.PROTECTED,
        hostname="localhost",
        ip_address=ip_address,
        os_version=f"{os_name} {platform.release()}",
        guardian_active=True,
        notes="Auto-registered: local Guardian host machine",
        metadata={
            "auto_registered": True,
            "os": os_name,
            "architecture": platform.machine(),
        },
    )

    try:
        inventory.register(asset)
        logger.info(
            "LocalDefender: registered localhost asset as '%s' (%s %s)",
            hostname, os_name, ip_address,
        )
        return True
    except Exception as exc:
        logger.warning("LocalDefender: could not register localhost asset: %s", exc)
        return False


def _get_local_ip() -> str:
    """Return a best-effort non-loopback LAN IP, or 127.0.0.1."""
    import socket
    try:
        # Connect to a public address to learn which interface is the default
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"
